# --- Serving options --- #
# If you are building a simple GitHub user page (username.github.io) then use these settings:
# url is the full website URL
url: "http://menggf.github.io"
# baseurl is the website's URL without the hostname
baseurl: ""

# Name of website
title: Computational Drug discovery
# Short description of your site
description: We develop new computational methods and apply them to identify drugs for age-depedent chronic diseases, especially including Azheimer's disease.

# --- Navigation bar options --- #
# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/DerekOgle.jpg"

# List of links in the navigation bar
navbar-links:
  About Us: "aboutus"
  Resource: 
        - Softwares: "resource#software"
        - Web tools: "resource#webtools"
        - Data: "resource#data"
  People: "personal"
  Publication: "publication"
  Contact: "contact"
  Home: "https://menggf.github.io"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Guofeng Meng
  email: "menggf@shutcm.edu.cn"
  github: menggf
  #twitter: droglenc

# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: false
  email: true
  twitter: true
  github: true
  linkedin: false
  stackoverflow: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "menggf.github.io"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: "UA-67615311-1"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "China/Shanghai"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md

# prose.io options
prose:
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - /_includes
    - /_layouts
    - /css
    - /img
    - /js
